<a href="https://colab.research.google.com/github/raviakasapu/EDA_ML/blob/main/1_EDA_ML_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EDA Fundamentals

https://github.com/PacktPublishing/Hands-on-Exploratory-Data-Analysis-with-Python

In [1]:
import numpy as np

In [2]:
my1DArray = np.array([1, 8, 27, 64])
print(my1DArray)

[ 1  8 27 64]


In [3]:
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print(my2DArray)

[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]


In [4]:
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]])
print(my3Darray)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [5]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
zeros = np.zeros((2,3,4),dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [7]:
np.random.random((2,2))

array([[0.29140338, 0.34415007],
       [0.81338556, 0.18398157]])

In [8]:
emptyArray = np.empty((3,2))
print(emptyArray)

[[1.09236887e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [9]:
fullArray = np.full((2,2),7)
print(fullArray)

[[7 7]
 [7 7]]


In [10]:
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

[10 15 20]


In [11]:
evenSpacedArray2 = np.linspace(0,2,9)
print(evenSpacedArray2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### broadcasting

In [14]:
A =np.ones((6, 8))
B = np.random.random((6,8))
A, B

(array([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[0.54209332, 0.11246739, 0.88743733, 0.46906034, 0.68005691,
         0.6883916 , 0.35441155, 0.52300594],
        [0.84398982, 0.06983876, 0.28695771, 0.98381645, 0.95340693,
         0.08586412, 0.49349314, 0.60639928],
        [0.05701944, 0.49101736, 0.53736455, 0.05694742, 0.19671163,
         0.23555056, 0.36876114, 0.76452357],
        [0.14793248, 0.02431284, 0.45296042, 0.83218389, 0.1378893 ,
         0.41524354, 0.88722787, 0.26254498],
        [0.55398137, 0.5364068 , 0.5239253 , 0.13339861, 0.54862156,
         0.06165706, 0.79170136, 0.42953944],
        [0.01158269, 0.94995509, 0.38401214, 0.81747252, 0.88520931,
         0.36476056, 0.24117504, 0.29771875]]))

In [15]:
print(A + B)

[[1.54209332 1.11246739 1.88743733 1.46906034 1.68005691 1.6883916
  1.35441155 1.52300594]
 [1.84398982 1.06983876 1.28695771 1.98381645 1.95340693 1.08586412
  1.49349314 1.60639928]
 [1.05701944 1.49101736 1.53736455 1.05694742 1.19671163 1.23555056
  1.36876114 1.76452357]
 [1.14793248 1.02431284 1.45296042 1.83218389 1.1378893  1.41524354
  1.88722787 1.26254498]
 [1.55398137 1.5364068  1.5239253  1.13339861 1.54862156 1.06165706
  1.79170136 1.42953944]
 [1.01158269 1.94995509 1.38401214 1.81747252 1.88520931 1.36476056
  1.24117504 1.29771875]]


In [16]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
y = np.arange(4)
print(y)

[0 1 2 3]


In [18]:
x-y

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [20]:
x = np.array([10, 20, 30, 40, 50])
print(x[0:2])

[10 20]


In [23]:
y = np.array([[ 1,  2,  3,  4], [ 9, 10, 11 ,12]])
print(y)
print(y[0:2, 1])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 2 10]


In [22]:
biggerThan2 = (y >= 2)
print(y[biggerThan2])

[ 2  3  4  9 10 11 12]


# pandas