<a href="https://colab.research.google.com/github/raviakasapu/EDA_ML/blob/main/1_EDA_ML_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EDA Fundamentals

https://github.com/PacktPublishing/Hands-on-Exploratory-Data-Analysis-with-Python

In [1]:
import numpy as np

In [2]:
my1DArray = np.array([1, 8, 27, 64])
print(my1DArray)

[ 1  8 27 64]


In [3]:
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print(my2DArray)

[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]


In [4]:
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]])
print(my3Darray)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [5]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
zeros = np.zeros((2,3,4),dtype=np.int16)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [7]:
np.random.random((2,2))

array([[0.29140338, 0.34415007],
       [0.81338556, 0.18398157]])

In [8]:
emptyArray = np.empty((3,2))
print(emptyArray)

[[1.09236887e-316 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]


In [9]:
fullArray = np.full((2,2),7)
print(fullArray)

[[7 7]
 [7 7]]


In [10]:
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

[10 15 20]


In [11]:
evenSpacedArray2 = np.linspace(0,2,9)
print(evenSpacedArray2)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### broadcasting

In [14]:
A =np.ones((6, 8))
B = np.random.random((6,8))
A, B

(array([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]),
 array([[0.54209332, 0.11246739, 0.88743733, 0.46906034, 0.68005691,
         0.6883916 , 0.35441155, 0.52300594],
        [0.84398982, 0.06983876, 0.28695771, 0.98381645, 0.95340693,
         0.08586412, 0.49349314, 0.60639928],
        [0.05701944, 0.49101736, 0.53736455, 0.05694742, 0.19671163,
         0.23555056, 0.36876114, 0.76452357],
        [0.14793248, 0.02431284, 0.45296042, 0.83218389, 0.1378893 ,
         0.41524354, 0.88722787, 0.26254498],
        [0.55398137, 0.5364068 , 0.5239253 , 0.13339861, 0.54862156,
         0.06165706, 0.79170136, 0.42953944],
        [0.01158269, 0.94995509, 0.38401214, 0.81747252, 0.88520931,
         0.36476056, 0.24117504, 0.29771875]]))

In [15]:
print(A + B)

[[1.54209332 1.11246739 1.88743733 1.46906034 1.68005691 1.6883916
  1.35441155 1.52300594]
 [1.84398982 1.06983876 1.28695771 1.98381645 1.95340693 1.08586412
  1.49349314 1.60639928]
 [1.05701944 1.49101736 1.53736455 1.05694742 1.19671163 1.23555056
  1.36876114 1.76452357]
 [1.14793248 1.02431284 1.45296042 1.83218389 1.1378893  1.41524354
  1.88722787 1.26254498]
 [1.55398137 1.5364068  1.5239253  1.13339861 1.54862156 1.06165706
  1.79170136 1.42953944]
 [1.01158269 1.94995509 1.38401214 1.81747252 1.88520931 1.36476056
  1.24117504 1.29771875]]


In [16]:
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
y = np.arange(4)
print(y)

[0 1 2 3]


In [18]:
x-y

array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [20]:
x = np.array([10, 20, 30, 40, 50])
print(x[0:2])

[10 20]


In [23]:
y = np.array([[ 1,  2,  3,  4], [ 9, 10, 11 ,12]])
print(y)
print(y[0:2, 1])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[ 2 10]


In [22]:
biggerThan2 = (y >= 2)
print(y[biggerThan2])

[ 2  3  4  9 10 11 12]


# pandas

In [24]:
import pandas as pd

In [25]:
print("Pandas Version:", pd.__version__)

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

Pandas Version: 1.3.5


In [26]:
series = pd.Series([2, 3, 7, 11, 13, 17, 19, 23])
print(series)


0     2
1     3
2     7
3    11
4    13
5    17
6    19
7    23
dtype: int64


In [27]:
dict_df = [{'A': 'Apple', 'B': 'Ball'},
           {'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}]
dict_df = pd.DataFrame(dict_df)
print(dict_df)

           A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat


In [28]:
series_df = pd.DataFrame({
    'A': range(1, 5),
    'B': pd.Timestamp('20190526'),
    'C': pd.Series(5, index=list(range(4)), dtype='float64'),
    'D': np.array([3] * 4, dtype='int64'),
    'E': pd.Categorical(["Depression", "Social Anxiety", "Bipolar Disorder", "Eating Disorder"]),
    'F': 'Mental health',
    'G': 'is challenging'
})
print(series_df)

   A          B    C  D                 E              F               G
0  1 2019-05-26  5.0  3        Depression  Mental health  is challenging
1  2 2019-05-26  5.0  3    Social Anxiety  Mental health  is challenging
2  3 2019-05-26  5.0  3  Bipolar Disorder  Mental health  is challenging
3  4 2019-05-26  5.0  3   Eating Disorder  Mental health  is challenging


In [29]:
sdf = {
    'County':['Østfold', 'Hordaland', 'Oslo', 'Hedmark', 'Oppland', 'Buskerud'],
    'ISO-Code':[1,2,3,4,5,6],
    'Area': [4180.69, 4917.94, 454.07, 27397.76, 25192.10, 14910.94],
    'Administrative centre': ["Sarpsborg", "Oslo", "City of Oslo", "Hamar", "Lillehammer", "Drammen"]
    }
sdf = pd.DataFrame(sdf)
print(sdf)

      County  ISO-Code      Area Administrative centre
0    Østfold         1   4180.69             Sarpsborg
1  Hordaland         2   4917.94                  Oslo
2       Oslo         3    454.07          City of Oslo
3    Hedmark         4  27397.76                 Hamar
4    Oppland         5  25192.10           Lillehammer
5   Buskerud         6  14910.94               Drammen


### import data set

In [30]:
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender','capital_gain','capital_loss','hours_per_week','country_of_origin','income']
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns)
df.head(10)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship ethnicity  \
0           Never-married        Adm-clerical   Not-in-family     White   
1      Married-civ-spouse     Exec-managerial         Husband     White   
2                Divorced   Handlers-cleaners   Not-in-family     White   
3      Married-civ-spouse   Handlers-cleaners         Husband     Black   
4      Married-civ-spouse      Prof-specialty            Wife     Black   
5      Married-civ-spouse     Exec-managerial            Wife     White   
6   Married-spouse-absent       Other-service   Not-in-family     Black   
7      Married-civ-spouse     Exec-managerial         Husband     White   
8           Never-married      Prof-specialty   Not-in-family     White   
9      Married-civ-spouse     Exec-managerial         Husband     White   

    gender  capital_gain  capital_loss  hours_per_week country_of_origin  \
0     Male          2174             0              40     United-States   
1     Male             0             0              13     United-States   
2     Male             0             0              40     United-States   
3     Male             0             0              40     United-States   
4   Female             0             0              40              Cuba   
5   Female             0             0              40     United-States   
6   Female             0             0              16           Jamaica   
7     Male             0             0              45     United-States   
8   Female         14084             0              50     United-States   
9     Male          5178             0              40     United-States   

   income  
0   <=50K  
1   <=50K  
2   <=50K  
3   <=50K  
4   <=50K  
5   <=50K  
6   <=50K  
7    >50K  
8    >50K  
9    >50K

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   age                32561 non-null  int64 
 1   workclass          32561 non-null  object
 2   fnlwgt             32561 non-null  int64 
 3   education          32561 non-null  object
 4   education_num      32561 non-null  int64 
 5   marital_status     32561 non-null  object
 6   occupation         32561 non-null  object
 7   relationship       32561 non-null  object
 8   ethnicity          32561 non-null  object
 9   gender             32561 non-null  object
 10  capital_gain       32561 non-null  int64 
 11  capital_loss       32561 non-null  int64 
 12  hours_per_week     32561 non-null  int64 
 13  country_of_origin  32561 non-null  object
 14  income             32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [32]:
df.shape

(32561, 15)

In [33]:
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
       'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
       'income'],
      dtype='object')

In [34]:
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [35]:
df.iloc[10]

age                                   37
workclass                        Private
fnlwgt                            280464
education                   Some-college
education_num                         10
marital_status        Married-civ-spouse
occupation               Exec-managerial
relationship                     Husband
ethnicity                          Black
gender                              Male
capital_gain                           0
capital_loss                           0
hours_per_week                        80
country_of_origin          United-States
income                              >50K
Name: 10, dtype: object

In [36]:
df.iloc[0:10]

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship ethnicity  \
0           Never-married        Adm-clerical   Not-in-family     White   
1      Married-civ-spouse     Exec-managerial         Husband     White   
2                Divorced   Handlers-cleaners   Not-in-family     White   
3      Married-civ-spouse   Handlers-cleaners         Husband     Black   
4      Married-civ-spouse      Prof-specialty            Wife     Black   
5      Married-civ-spouse     Exec-managerial            Wife     White   
6   Married-spouse-absent       Other-service   Not-in-family     Black   
7      Married-civ-spouse     Exec-managerial         Husband     White   
8           Never-married      Prof-specialty   Not-in-family     White   
9      Married-civ-spouse     Exec-managerial         Husband     White   

    gender  capital_gain  capital_loss  hours_per_week country_of_origin  \
0     Male          2174             0              40     United-States   
1     Male             0             0              13     United-States   
2     Male             0             0              40     United-States   
3     Male             0             0              40     United-States   
4   Female             0             0              40              Cuba   
5   Female             0             0              40     United-States   
6   Female             0             0              16           Jamaica   
7     Male             0             0              45     United-States   
8   Female         14084             0              50     United-States   
9     Male          5178             0              40     United-States   

   income  
0   <=50K  
1   <=50K  
2   <=50K  
3   <=50K  
4   <=50K  
5   <=50K  
6   <=50K  
7    >50K  
8    >50K  
9    >50K

In [37]:
df.iloc[10:15]

age   workclass  fnlwgt      education  education_num  \
10   37     Private  280464   Some-college             10   
11   30   State-gov  141297      Bachelors             13   
12   23     Private  122272      Bachelors             13   
13   32     Private  205019     Assoc-acdm             12   
14   40     Private  121772      Assoc-voc             11   

         marital_status        occupation    relationship  \
10   Married-civ-spouse   Exec-managerial         Husband   
11   Married-civ-spouse    Prof-specialty         Husband   
12        Never-married      Adm-clerical       Own-child   
13        Never-married             Sales   Not-in-family   
14   Married-civ-spouse      Craft-repair         Husband   

              ethnicity   gender  capital_gain  capital_loss  hours_per_week  \
10                Black     Male             0             0              80   
11   Asian-Pac-Islander     Male             0             0              40   
12                White   Female             0             0              30   
13                Black     Male             0             0              50   
14   Asian-Pac-Islander     Male             0             0              40   

   country_of_origin  income  
10     United-States    >50K  
11             India    >50K  
12     United-States   <=50K  
13     United-States   <=50K  
14                 ?    >50K

In [39]:
df.iloc[-2:]

age      workclass  fnlwgt education  education_num  \
32559   22        Private  201490   HS-grad              9   
32560   52   Self-emp-inc  287927   HS-grad              9   

            marital_status        occupation relationship ethnicity   gender  \
32559        Never-married      Adm-clerical    Own-child     White     Male   
32560   Married-civ-spouse   Exec-managerial         Wife     White   Female   

       capital_gain  capital_loss  hours_per_week country_of_origin  income  
32559             0             0              20     United-States   <=50K  
32560         15024             0              40     United-States    >50K

In [44]:
df.iloc[1::10,3:5].head()

education  education_num
1       Bachelors             13
11      Bachelors             13
21        HS-grad              9
31   Some-college             10
41      Bachelors             13

In [45]:
np.random.seed(24)
df = pd.DataFrame({'F': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 5), columns=list('EDCBA'))],
               axis=1)
df.iloc[0, 2] = np.nan
df

F         E         D         C         B         A
0   1.0  1.329212       NaN -0.316280 -0.990810 -1.070816
1   2.0 -1.438713  0.564417  0.295722 -1.626404  0.219565
2   3.0  0.678805  1.889273  0.961538  0.104011 -0.481165
3   4.0  0.850229  1.453425  1.057737  0.165562  0.515018
4   5.0 -1.336936  0.562861  1.392855 -0.063328  0.121668
5   6.0  1.207603 -0.002040  1.627796  0.354493  1.037528
6   7.0 -0.385684  0.519818  1.686583 -1.325963  1.428984
7   8.0 -2.089354 -0.129820  0.631523 -0.586538  0.290720
8   9.0  1.264103  0.290035 -1.970288  0.803906  1.030550
9  10.0  0.118098 -0.021853  0.046841 -1.628753 -0.392361

In [46]:
def colorNegativeValueToRed(value):
  if value < 0:
    color = 'red'
  elif value > 0:
    color = 'black'
  else:
    color = 'green'

  return 'color: %s' % color

In [47]:
s = df.style.applymap(colorNegativeValueToRed, subset=['A','B','C','D','E'])
s

In [48]:
def highlightMax(s):
    isMax = s == s.max()
    return ['background-color: orange' if v else '' for v in isMax]

def highlightMin(s):
    isMin = s == s.min()
    return ['background-color: green' if v else '' for v in isMin]

In [49]:
df.style.apply(highlightMax).apply(highlightMin).highlight_null(null_color='red')

In [50]:
import seaborn as sns

In [51]:
cm = sns.light_palette("pink", as_cmap=True)

s = df.style.background_gradient(cmap=cm)
s